// GENERATED by scripts/bundle-migrations.ts from db/migrations/*.sql — do not edit.
// Regenerate with `npm run db:generate`.

export type Migration = { name: string; statements: string[] }

export const MIGRATIONS: readonly Migration[] = [
  {
    "name": "0000_init_app_plane",
    "statements": [
      "CREATE TABLE `account` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`account_id` text NOT NULL,\n\t`provider_id` text NOT NULL,\n\t`access_token` text,\n\t`refresh_token` text,\n\t`access_token_expires_at` integer,\n\t`refresh_token_expires_at` integer,\n\t`scope` text,\n\t`id_token` text,\n\t`password` text,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\t`updated_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `account_provider_unique` ON `account` (`provider_id`,`account_id`);",
      "CREATE INDEX `account_user_idx` ON `account` (`user_id`);",
      "CREATE TABLE `saved_building` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`numero_dpe` text NOT NULL,\n\t`note` text,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\t`updated_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `saved_building_user_dpe_unique` ON `saved_building` (`user_id`,`numero_dpe`);",
      "CREATE INDEX `saved_building_user_idx` ON `saved_building` (`user_id`);",
      "CREATE TABLE `saved_search` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`spec` text NOT NULL,\n\t`visibility` text DEFAULT 'private' NOT NULL,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\t`updated_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,\n\tCONSTRAINT \"saved_search_visibility_known\" CHECK(\"saved_search\".\"visibility\" in ('private', 'unlisted'))\n);",
      "CREATE INDEX `saved_search_user_idx` ON `saved_search` (`user_id`);",
      "CREATE TABLE `session` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`token` text NOT NULL,\n\t`user_id` text NOT NULL,\n\t`expires_at` integer NOT NULL,\n\t`ip_address` text,\n\t`user_agent` text,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\t`updated_at` integer DEFAULT (unixepoch()) NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade\n);",
      "CREATE UNIQUE INDEX `session_token_unique` ON `session` (`token`);",
      "CREATE INDEX `session_user_idx` ON `session` (`user_id`);",
      "CREATE TABLE `user` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`email` text NOT NULL,\n\t`email_verified` integer DEFAULT false NOT NULL,\n\t`image` text,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\t`updated_at` integer DEFAULT (unixepoch()) NOT NULL\n);",
      "CREATE UNIQUE INDEX `user_email_unique` ON `user` (`email`);",
      "CREATE TABLE `verification` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`identifier` text NOT NULL,\n\t`value` text NOT NULL,\n\t`expires_at` integer NOT NULL,\n\t`created_at` integer DEFAULT (unixepoch()) NOT NULL,\n\t`updated_at` integer DEFAULT (unixepoch()) NOT NULL\n);",
      "CREATE INDEX `verification_identifier_idx` ON `verification` (`identifier`);"
    ]
  }
] as const
