/**
 * Turns db/migrations/*.sql into db/migrations.generated.ts.
 *
 * Why this exists: the Worker is bundled by esbuild, which does not include .sql
 * files, and D1 takes one statement per call. So the migrations have to reach
 * the deployed Worker as data, already split.
 *
 * The .sql files stay the human-readable artefact — reviewable in a diff, runnable
 * through `wrangler d1 execute`. This module is derived from them and committed so
 * the deployed bundle needs no filesystem. `npm run db:generate` regenerates both;
 * `npm run db:check` fails if the committed copy is stale, because editing the
 * schema without regenerating reaches a database as nothing at all.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const migrationsDir = fileURLToPath(new URL('../db/migrations/', import.meta.url))
const outPath = fileURLToPath(new URL('../db/migrations.generated.ts', import.meta.url))

const files = readdirSync(migrationsDir)
  .filter((f) => f.endsWith('.sql'))
  .sort() // filenames are zero-padded and ordered by drizzle-kit; order is the contract

const migrations = files.map((file) => ({
  name: file.replace(/\.sql$/, ''),
  statements: readFileSync(migrationsDir + file, 'utf8')
    .split('--> statement-breakpoint')
    .map((s) => s.trim())
    .filter((s) => s.length > 0),
}))

const body = `// GENERATED by scripts/bundle-migrations.ts from db/migrations/*.sql — do not edit.
// Regenerate with \`npm run db:generate\`.

export type Migration = { name: string; statements: string[] }

export const MIGRATIONS: readonly Migration[] = ${JSON.stringify(migrations, null, 2)} as const
`

writeFileSync(outPath, body)
console.log(`wrote ${migrations.length} migration(s) to db/migrations.generated.ts`)
